/**
 * Build-time API extraction CLI (Phase D).
 *
 * Runs via the Nx `docs:extract-api` target (a `dependsOn` of `docs:build` and
 * `docs:serve`). For every docs page that maps to a library it writes
 * `apps/docs/src/generated/api/<name>.json` (an {@link ApiEntry}) plus a
 * generated `index.ts` module map so a page can lazily import its lib's entry
 * by kebab name.
 *
 * `apps/docs/src/generated/` is git-ignored and regenerated in place on every
 * build (see `./generated-output` for why the directory is never removed); the
 * extraction logic itself lives in `./api-extractor` so it can be unit tested
 * without triggering file writes.
 */
import * as path from 'node:path';
import {
  createApiProject,
  extractEntry,
  findRepoRoot,
  listDocumentedPages,
  resolveLib,
} from './api-extractor';
import { syncGeneratedDir } from './generated-output';

/** Absolute path to the generated-output directory, relative to the workspace root. */
const OUTPUT_SUBDIR = path.join('apps', 'docs', 'src', 'generated', 'api');

function main(): void {
  const repoRoot = findRepoRoot(process.cwd());
  const outDir = path.join(repoRoot, OUTPUT_SUBDIR);

  const project = createApiProject(repoRoot);
  const pages = listDocumentedPages(repoRoot);

  const files = new Map<string, string>();
  const extracted: string[] = [];
  const skipped: string[] = [];
  let symbolCount = 0;

  for (const page of pages) {
    const lib = resolveLib(repoRoot, page);
    if (!lib) {
      skipped.push(page);
      continue;
    }
    const entry = extractEntry(project, page, lib.indexPath);
    files.set(`${page}.json`, `${JSON.stringify(entry, null, 2)}\n`);
    extracted.push(page);
    symbolCount += entry.symbols.length;
  }
  files.set('index.ts', renderModuleMap(extracted));

  // Regenerated in place: unchanged files are left alone (no rebuild for the
  // dev server), changed ones are swapped atomically, and pages/libs that no
  // longer exist are pruned afterwards so no stale JSON is left behind.
  const { written, removed } = syncGeneratedDir(outDir, files);

  console.log(
    `[extract-api] Extracted ${extracted.length} API entr${extracted.length === 1 ? 'y' : 'ies'} ` +
      `(${symbolCount} symbols) into ${path.relative(repoRoot, outDir)}: ` +
      `${written.length} file(s) changed, ${removed.length} stale file(s) removed`,
  );
  if (skipped.length) {
    console.log(
      `[extract-api] Skipped ${skipped.length} page(s) with no matching library: ${skipped.join(', ')}`,
    );
  }
}

/** Renders the generated `index.ts` module map of lazy per-page API loaders. */
function renderModuleMap(names: readonly string[]): string {
  const sorted = [...names].sort();
  const loaderLines = sorted
    .map(
      (name) =>
        `  '${name}': () => import('./${name}.json').then((m) => m.default as ApiEntry),`,
    )
    .join('\n');

  return `// AUTO-GENERATED by apps/docs/tools/extract-api.ts — do not edit by hand.
// Regenerated on every \`nx build docs\` / \`nx serve docs\` via the \`extract-api\` target.
import type { ApiEntry } from '../../app/shared/api-viewer/api.types';

/**
 * Lazy loaders for each documented library's extracted API entry, keyed by
 * docs-page (kebab) name. Each loader resolves the page-specific JSON chunk on
 * demand so no API data lands in the initial bundle.
 */
export const apiEntryLoaders: Record<string, () => Promise<ApiEntry>> = {
${loaderLines}
};

/** Docs-page names that have an extracted API entry. */
export type ApiEntryName = keyof typeof apiEntryLoaders;

/** Whether an extracted API entry exists for the given docs-page name. */
export function hasApiEntry(name: string): boolean {
  return Object.prototype.hasOwnProperty.call(apiEntryLoaders, name);
}
`;
}

try {
  main();
} catch (error) {
  console.error('[extract-api] Extraction failed:', error);
  process.exit(1);
}
