import type {
  MlvDataTableColumn,
  MlvDataTablePresentationState,
} from '@malva-ui/core/data-table';
import type {
  MlvFilterDefinition,
  MlvFilterExpression,
  MlvFilterFieldState,
} from '@malva-ui/core/filter';
import type { MlvViewVariant } from '@malva-ui/core/view-variant';

export interface Account {
  readonly id: string;
  readonly name: string;
  readonly owner: string | null;
  readonly plan: 'Enterprise' | 'Professional' | 'Growth';
  readonly arr: number;
  readonly health: 'At risk' | 'Watch' | 'Healthy';
  readonly renewalDate: string;
  readonly renewalDays: number;
  readonly lastActivity: string;
}

export interface AccountsViewState {
  readonly search: string;
  readonly filterExpression: MlvFilterExpression;
  readonly table: MlvDataTablePresentationState;
}

const account = (
  id: string,
  name: string,
  owner: string | null,
  plan: Account['plan'],
  arr: number,
  health: Account['health'],
  renewalDate: string,
  renewalDays: number,
  lastActivity: string,
): Account => ({
  id,
  name,
  owner,
  plan,
  arr,
  health,
  renewalDate,
  renewalDays,
  lastActivity,
});

/** Stable account data keeps the table and every saved-view count reproducible. */
export const ACCOUNTS: Account[] = [
  account(
    'acme',
    'Acme Corporation',
    null,
    'Enterprise',
    245000,
    'At risk',
    '2026-09-12',
    23,
    '2 days ago',
  ),
  account(
    'northwind',
    'Northwind Traders',
    null,
    'Enterprise',
    198000,
    'Watch',
    '2026-09-18',
    29,
    '1 day ago',
  ),
  account(
    'globex',
    'Globex Industries',
    null,
    'Enterprise',
    156000,
    'Healthy',
    '2026-09-25',
    36,
    '5 days ago',
  ),
  account(
    'initech',
    'Initech',
    null,
    'Professional',
    82000,
    'At risk',
    '2026-10-03',
    44,
    '4 days ago',
  ),
  account(
    'umbrella',
    'Umbrella Corp',
    null,
    'Enterprise',
    310000,
    'Watch',
    '2026-10-07',
    48,
    '3 days ago',
  ),
  account(
    'stark',
    'Stark Industries',
    null,
    'Enterprise',
    425000,
    'Healthy',
    '2026-10-12',
    53,
    '6 days ago',
  ),
  account(
    'wayne',
    'Wayne Enterprises',
    null,
    'Enterprise',
    275000,
    'At risk',
    '2026-10-18',
    59,
    '1 day ago',
  ),
  account(
    'soylent',
    'Soylent Corp',
    null,
    'Professional',
    64000,
    'Watch',
    '2026-10-22',
    60,
    '2 days ago',
  ),
  account(
    'aperture',
    'Aperture Science',
    'Alina Pop',
    'Enterprise',
    182000,
    'Watch',
    '2026-11-09',
    81,
    'Today',
  ),
  account(
    'hooli',
    'Hooli',
    'Mihai Ionescu',
    'Enterprise',
    396000,
    'At risk',
    '2026-11-15',
    87,
    '3 days ago',
  ),
  account(
    'oscorp',
    'Oscorp',
    'Sofia Marin',
    'Professional',
    112000,
    'Watch',
    '2026-11-24',
    96,
    '1 day ago',
  ),
  account(
    'wonka',
    'Wonka Industries',
    'Alina Pop',
    'Growth',
    48000,
    'Healthy',
    '2026-12-02',
    104,
    'Today',
  ),
  account(
    'cyberdyne',
    'Cyberdyne Systems',
    'Mihai Ionescu',
    'Enterprise',
    335000,
    'At risk',
    '2026-12-14',
    116,
    '8 days ago',
  ),
  account(
    'vehement',
    'Vehement Capital',
    'Sofia Marin',
    'Professional',
    92000,
    'Watch',
    '2026-12-19',
    121,
    '4 days ago',
  ),
  account(
    'tyrell',
    'Tyrell Corporation',
    'Alina Pop',
    'Enterprise',
    215000,
    'Healthy',
    '2027-01-04',
    137,
    'Today',
  ),
  account(
    'massive',
    'Massive Dynamic',
    'Mihai Ionescu',
    'Professional',
    78000,
    'At risk',
    '2027-01-17',
    150,
    '6 days ago',
  ),
  account(
    'prestige',
    'Prestige Worldwide',
    'Sofia Marin',
    'Growth',
    36000,
    'Watch',
    '2027-01-24',
    157,
    '2 days ago',
  ),
  account(
    'pied-piper',
    'Pied Piper',
    'Alina Pop',
    'Growth',
    58000,
    'Healthy',
    '2027-02-03',
    167,
    'Today',
  ),
  account(
    'vandalay',
    'Vandelay Industries',
    'Mihai Ionescu',
    'Professional',
    86000,
    'At risk',
    '2027-02-12',
    176,
    '5 days ago',
  ),
  account(
    'dharma',
    'Dharma Initiative',
    'Sofia Marin',
    'Enterprise',
    265000,
    'Watch',
    '2027-02-20',
    184,
    '3 days ago',
  ),
  account(
    'gringotts',
    'Gringotts Bank',
    'Alina Pop',
    'Enterprise',
    504000,
    'Healthy',
    '2027-03-02',
    194,
    'Today',
  ),
  account(
    'monarch',
    'Monarch Solutions',
    'Mihai Ionescu',
    'Professional',
    97000,
    'At risk',
    '2027-03-16',
    208,
    '9 days ago',
  ),
  account(
    'globomantics',
    'Globomantics',
    'Sofia Marin',
    'Growth',
    41000,
    'Watch',
    '2027-03-27',
    219,
    '1 day ago',
  ),
  account(
    'initech-north',
    'Initech North',
    'Alina Pop',
    'Professional',
    68000,
    'At risk',
    '2027-04-06',
    229,
    'Today',
  ),
  account(
    'paper-street',
    'Paper Street Soap',
    'Mihai Ionescu',
    'Growth',
    24000,
    'Healthy',
    '2027-04-17',
    240,
    '4 days ago',
  ),
  account(
    'fabrikam',
    'Fabrikam',
    'Sofia Marin',
    'Enterprise',
    188000,
    'Watch',
    '2027-05-01',
    254,
    '2 days ago',
  ),
  account(
    'contoso',
    'Contoso Ltd',
    'Alina Pop',
    'Professional',
    74000,
    'At risk',
    '2027-05-13',
    266,
    'Today',
  ),
  account(
    'tailspin',
    'Tailspin Toys',
    'Mihai Ionescu',
    'Growth',
    39000,
    'Healthy',
    '2027-05-25',
    278,
    '7 days ago',
  ),
  account(
    'adventure',
    'Adventure Works',
    'Sofia Marin',
    'Enterprise',
    295000,
    'Watch',
    '2027-06-04',
    288,
    '3 days ago',
  ),
  account(
    'litware',
    'Litware Inc',
    'Alina Pop',
    'Professional',
    106000,
    'At risk',
    '2027-06-18',
    302,
    'Today',
  ),
  account(
    'proseware',
    'Proseware',
    'Mihai Ionescu',
    'Growth',
    47000,
    'Healthy',
    '2027-07-02',
    316,
    '5 days ago',
  ),
  account(
    'blue-yonder',
    'Blue Yonder Airlines',
    'Sofia Marin',
    'Enterprise',
    349000,
    'Watch',
    '2027-07-15',
    329,
    '1 day ago',
  ),
  account(
    'woodgrove',
    'Woodgrove Bank',
    'Alina Pop',
    'Enterprise',
    271000,
    'At risk',
    '2027-08-01',
    346,
    'Today',
  ),
  account(
    'humongous',
    'Humongous Insurance',
    'Mihai Ionescu',
    'Professional',
    89000,
    'Healthy',
    '2027-08-19',
    364,
    '2 days ago',
  ),
];

export const DEFAULT_TABLE_STATE: MlvDataTablePresentationState = {
  sort: { key: 'renewalDate', direction: 'asc' },
  visibleColumnKeys: [
    'name',
    'owner',
    'plan',
    'arr',
    'health',
    'renewalDate',
    'lastActivity',
  ],
  pinnedStartColumnKeys: ['name'],
  pinnedEndColumnKeys: [],
  columnWidths: {},
  perPage: 25,
};

export const AT_RISK_EXPRESSION: MlvFilterExpression = {
  kind: 'group',
  combinator: 'and',
  children: [
    {
      kind: 'condition',
      key: 'health',
      condition: { operator: 'equals', value: 'At risk' },
    },
    {
      kind: 'condition',
      key: 'renewalDays',
      condition: { operator: 'less-than-or-equal', value: 60 },
    },
    {
      kind: 'condition',
      key: 'owner',
      condition: { operator: 'empty', value: null },
    },
  ],
};

export const AT_RISK_FILTERS: readonly MlvFilterFieldState[] = [
  {
    key: 'health',
    strategy: 'and',
    conditions: [{ operator: 'equals', value: 'At risk' }],
  },
  {
    key: 'renewalDays',
    strategy: 'and',
    conditions: [{ operator: 'less-than-or-equal', value: 60 }],
  },
  {
    key: 'owner',
    strategy: 'and',
    conditions: [{ operator: 'empty', value: null }],
  },
];

export const FILTER_DEFINITIONS: readonly MlvFilterDefinition[] = [
  {
    key: 'health',
    label: 'Health',
    options: ['At risk', 'Watch', 'Healthy'].map((value) => ({
      label: value,
      value,
    })),
  },
  {
    key: 'renewalDays',
    label: 'Renewal',
    editor: 'number',
    operators: ['less-than-or-equal', 'greater-than-or-equal'],
  },
  {
    key: 'owner',
    label: 'Owner',
    options: ['Alina Pop', 'Mihai Ionescu', 'Sofia Marin'].map((value) => ({
      label: value,
      value,
    })),
  },
  {
    key: 'plan',
    label: 'Plan',
    options: ['Enterprise', 'Professional', 'Growth'].map((value) => ({
      label: value,
      value,
    })),
  },
  {
    key: 'arr',
    label: 'ARR',
    editor: 'number',
    operators: ['greater-than-or-equal', 'less-than-or-equal'],
  },
];

export const ACCOUNT_COLUMNS: MlvDataTableColumn<Account>[] = [
  {
    key: 'name',
    title: 'Account',
    sortable: true,
    searchable: true,
    pinned: true,
    pinSide: 'left',
    width: '15rem',
  },
  {
    key: 'owner',
    title: 'Owner',
    hideable: true,
    searchable: true,
    width: '10rem',
  },
  {
    key: 'plan',
    title: 'Plan',
    hideable: true,
    searchable: true,
    width: '10rem',
  },
  {
    key: 'arr',
    title: 'ARR',
    sortable: true,
    hideable: true,
    align: 'right',
    width: '9rem',
  },
  {
    key: 'health',
    title: 'Health',
    hideable: true,
    searchable: true,
    width: '9rem',
  },
  {
    key: 'renewalDate',
    title: 'Renewal date',
    sortable: true,
    hideable: true,
    width: '11rem',
  },
  {
    key: 'lastActivity',
    title: 'Last activity',
    hideable: true,
    width: '10rem',
  },
];

const capabilities = (editable: boolean) => ({
  clone: !editable,
  update: editable,
  rename: false,
  delete: false,
  share: false,
});
const state = (
  filterExpression: MlvFilterExpression,
  table = DEFAULT_TABLE_STATE,
): AccountsViewState => ({ search: '', filterExpression, table });

export const ACCOUNT_VIEW_VARIANTS: readonly MlvViewVariant<AccountsViewState>[] =
  [
    {
      id: 'all-accounts',
      name: 'All accounts',
      scope: 'system',
      locked: true,
      resultCount: 34,
      capabilities: capabilities(false),
      state: state({ kind: 'group', combinator: 'and', children: [] }),
    },
    {
      id: 'at-risk',
      name: 'At risk',
      scope: 'system',
      locked: true,
      resultCount: 34,
      capabilities: capabilities(false),
      state: state(AT_RISK_EXPRESSION),
    },
    {
      id: 'enterprise-renewals',
      name: 'Enterprise renewals',
      scope: 'system',
      locked: true,
      resultCount: 18,
      capabilities: capabilities(false),
      state: state({
        kind: 'condition',
        key: 'plan',
        condition: { operator: 'equals', value: 'Enterprise' },
      }),
    },
    {
      id: 'unassigned',
      name: 'Unassigned',
      scope: 'system',
      locked: true,
      resultCount: 27,
      capabilities: capabilities(false),
      state: state({
        kind: 'condition',
        key: 'owner',
        condition: { operator: 'empty', value: null },
      }),
    },
    {
      id: 'overdue-renewals',
      name: 'Overdue renewals',
      scope: 'team',
      resultCount: 12,
      capabilities: capabilities(false),
      state: state({
        kind: 'condition',
        key: 'renewalDays',
        condition: { operator: 'less-than-or-equal', value: 30 },
      }),
    },
    {
      id: 'expansion-potential',
      name: 'Expansion potential',
      scope: 'team',
      resultCount: 41,
      capabilities: capabilities(false),
      state: state({
        kind: 'condition',
        key: 'arr',
        condition: { operator: 'greater-than-or-equal', value: 200000 },
      }),
    },
    {
      id: 'low-usage',
      name: 'Low usage',
      scope: 'team',
      resultCount: 15,
      capabilities: capabilities(false),
      state: state({
        kind: 'condition',
        key: 'health',
        condition: { operator: 'equals', value: 'At risk' },
      }),
    },
    {
      id: 'contracts-expiring',
      name: 'Contracts expiring',
      scope: 'team',
      resultCount: 9,
      capabilities: capabilities(false),
      state: state({
        kind: 'condition',
        key: 'renewalDays',
        condition: { operator: 'less-than-or-equal', value: 60 },
      }),
    },
    {
      id: 'my-follow-ups',
      name: 'My follow-ups',
      scope: 'personal',
      resultCount: 7,
      capabilities: capabilities(true),
      state: state({
        kind: 'condition',
        key: 'owner',
        condition: { operator: 'equals', value: 'Alina Pop' },
      }),
    },
    {
      id: 'recently-contacted',
      name: 'Recently contacted',
      scope: 'personal',
      resultCount: 23,
      capabilities: capabilities(true),
      state: state({ kind: 'group', combinator: 'and', children: [] }),
    },
  ];

export const AT_RISK_VIEW =
  ACCOUNT_VIEW_VARIANTS[1] as MlvViewVariant<AccountsViewState>;
