import { Component, signal, ChangeDetectionStrategy } from '@angular/core';
import {
  MlvSidebar,
  MlvSidebarGroup,
  MlvSidebarItem,
  MlvSidebarItemIcon,
  MlvSidebarItemTitle,
  MlvSidebarHeader,
  MlvSidebarFooter,
  SidebarContentDirective,
  MlvSidebarTrigger,
} from '@malva-ui/core/sidebar';
import { MlvAvatar } from '@malva-ui/core/avatar';
import { MlvDivider } from '@malva-ui/core/divider';
import {
  LucideActivity,
  LucideBox,
  LucideCircleHelp,
  LucideDatabase,
  LucideFileSearch,
  LucideFileText,
  LucideFolderOpen,
  LucideImage,
  LucideKey,
  LucideLayoutDashboard,
  LucideMail,
  LucideMessageSquare,
  LucideNewspaper,
  LucidePackage,
  LucidePanelLeftClose,
  LucidePanelLeftOpen,
  LucideServer,
  LucideSettings,
  LucideShield,
  LucideShieldCheck,
  LucideShoppingBag,
  LucideTag,
  LucideUser,
  LucideUsers,
  LucideWebhook,
} from '@lucide/angular';

@Component({
  selector: 'docs-sidebar-nested-submenus-example',
  imports: [
    MlvSidebar,
    MlvSidebarGroup,
    MlvSidebarItem,
    MlvSidebarItemIcon,
    MlvSidebarItemTitle,
    MlvSidebarHeader,
    MlvSidebarFooter,
    SidebarContentDirective,
    MlvSidebarTrigger,
    MlvAvatar,
    MlvDivider,
    LucideActivity,
    LucideBox,
    LucideCircleHelp,
    LucideDatabase,
    LucideFileSearch,
    LucideFileText,
    LucideFolderOpen,
    LucideImage,
    LucideKey,
    LucideLayoutDashboard,
    LucideMail,
    LucideMessageSquare,
    LucideNewspaper,
    LucidePackage,
    LucidePanelLeftClose,
    LucidePanelLeftOpen,
    LucideServer,
    LucideSettings,
    LucideShield,
    LucideShieldCheck,
    LucideShoppingBag,
    LucideTag,
    LucideUser,
    LucideUsers,
    LucideWebhook,
  ],
  templateUrl: './index.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
  styleUrl: './index.scss',
})
export default class SidebarNestedSubmenusExampleComponent {
  readonly collapsed = signal(false);
}
