import { Component, ChangeDetectionStrategy } from '@angular/core';
import type { MlvDataTableColumn } from '@malva-ui/core/data-table';
import { MlvDataTable, MlvDataTableCell } from '@malva-ui/core/data-table';
import { MlvBadge } from '@malva-ui/core/badge';

interface ServerMetric {
  host: string;
  region: string;
  status: 'healthy' | 'degraded' | 'down';
  cpu: number;
  memory: number;
  disk: number;
  network: string;
  uptime: string;
  requests: number;
  errors: number;
  latency: string;
  version: string;
  os: string;
  lastDeploy: string;
}

const SERVERS: ServerMetric[] = [
  {
    host: 'prod-api-01',
    region: 'us-east-1',
    status: 'healthy',
    cpu: 42,
    memory: 68,
    disk: 55,
    network: '1.2 Gbps',
    uptime: '45d 12h',
    requests: 12450,
    errors: 3,
    latency: '12ms',
    version: 'v3.8.1',
    os: 'Ubuntu 24.04',
    lastDeploy: '2026-04-01',
  },
  {
    host: 'prod-api-02',
    region: 'us-east-1',
    status: 'healthy',
    cpu: 38,
    memory: 72,
    disk: 48,
    network: '1.1 Gbps',
    uptime: '45d 12h',
    requests: 11890,
    errors: 1,
    latency: '14ms',
    version: 'v3.8.1',
    os: 'Ubuntu 24.04',
    lastDeploy: '2026-04-01',
  },
  {
    host: 'prod-api-03',
    region: 'eu-west-1',
    status: 'degraded',
    cpu: 87,
    memory: 91,
    disk: 72,
    network: '0.8 Gbps',
    uptime: '12d 6h',
    requests: 9540,
    errors: 45,
    latency: '89ms',
    version: 'v3.8.0',
    os: 'Ubuntu 24.04',
    lastDeploy: '2026-03-28',
  },
  {
    host: 'prod-worker-01',
    region: 'us-east-1',
    status: 'healthy',
    cpu: 65,
    memory: 54,
    disk: 30,
    network: '0.4 Gbps',
    uptime: '30d 8h',
    requests: 4200,
    errors: 0,
    latency: '—',
    version: 'v3.8.1',
    os: 'Debian 12',
    lastDeploy: '2026-04-01',
  },
  {
    host: 'prod-worker-02',
    region: 'eu-west-1',
    status: 'healthy',
    cpu: 51,
    memory: 60,
    disk: 35,
    network: '0.3 Gbps',
    uptime: '30d 8h',
    requests: 3800,
    errors: 2,
    latency: '—',
    version: 'v3.8.1',
    os: 'Debian 12',
    lastDeploy: '2026-04-01',
  },
  {
    host: 'prod-db-01',
    region: 'us-east-1',
    status: 'healthy',
    cpu: 28,
    memory: 82,
    disk: 67,
    network: '2.4 Gbps',
    uptime: '90d 3h',
    requests: 28900,
    errors: 0,
    latency: '3ms',
    version: 'PG 16.2',
    os: 'Amazon Linux',
    lastDeploy: '2026-02-15',
  },
  {
    host: 'prod-db-02',
    region: 'eu-west-1',
    status: 'healthy',
    cpu: 22,
    memory: 78,
    disk: 61,
    network: '2.1 Gbps',
    uptime: '90d 3h',
    requests: 25600,
    errors: 0,
    latency: '4ms',
    version: 'PG 16.2',
    os: 'Amazon Linux',
    lastDeploy: '2026-02-15',
  },
  {
    host: 'prod-cache-01',
    region: 'us-east-1',
    status: 'healthy',
    cpu: 15,
    memory: 45,
    disk: 12,
    network: '3.8 Gbps',
    uptime: '60d 1h',
    requests: 89000,
    errors: 0,
    latency: '1ms',
    version: 'Redis 7.4',
    os: 'Amazon Linux',
    lastDeploy: '2026-03-10',
  },
  {
    host: 'prod-cache-02',
    region: 'eu-west-1',
    status: 'down',
    cpu: 0,
    memory: 0,
    disk: 12,
    network: '0 Gbps',
    uptime: '0d 0h',
    requests: 0,
    errors: 0,
    latency: '—',
    version: 'Redis 7.4',
    os: 'Amazon Linux',
    lastDeploy: '2026-03-10',
  },
  {
    host: 'staging-api-01',
    region: 'us-west-2',
    status: 'healthy',
    cpu: 12,
    memory: 34,
    disk: 20,
    network: '0.2 Gbps',
    uptime: '7d 4h',
    requests: 560,
    errors: 12,
    latency: '22ms',
    version: 'v3.9.0-rc',
    os: 'Ubuntu 24.04',
    lastDeploy: '2026-04-08',
  },
  {
    host: 'staging-worker',
    region: 'us-west-2',
    status: 'healthy',
    cpu: 8,
    memory: 22,
    disk: 15,
    network: '0.1 Gbps',
    uptime: '7d 4h',
    requests: 140,
    errors: 5,
    latency: '—',
    version: 'v3.9.0-rc',
    os: 'Debian 12',
    lastDeploy: '2026-04-08',
  },
  {
    host: 'prod-cdn-01',
    region: 'us-east-1',
    status: 'healthy',
    cpu: 5,
    memory: 18,
    disk: 88,
    network: '9.2 Gbps',
    uptime: '120d 0h',
    requests: 450000,
    errors: 12,
    latency: '2ms',
    version: 'Nginx 1.27',
    os: 'Alpine 3.20',
    lastDeploy: '2026-01-20',
  },
  {
    host: 'prod-cdn-02',
    region: 'ap-south-1',
    status: 'healthy',
    cpu: 7,
    memory: 20,
    disk: 82,
    network: '8.5 Gbps',
    uptime: '120d 0h',
    requests: 380000,
    errors: 8,
    latency: '3ms',
    version: 'Nginx 1.27',
    os: 'Alpine 3.20',
    lastDeploy: '2026-01-20',
  },
  {
    host: 'prod-lb-01',
    region: 'us-east-1',
    status: 'healthy',
    cpu: 10,
    memory: 25,
    disk: 5,
    network: '10 Gbps',
    uptime: '180d 0h',
    requests: 520000,
    errors: 0,
    latency: '<1ms',
    version: 'HAProxy 3.0',
    os: 'Debian 12',
    lastDeploy: '2025-12-01',
  },
  {
    host: 'prod-lb-02',
    region: 'eu-west-1',
    status: 'healthy',
    cpu: 9,
    memory: 23,
    disk: 5,
    network: '10 Gbps',
    uptime: '180d 0h',
    requests: 490000,
    errors: 0,
    latency: '<1ms',
    version: 'HAProxy 3.0',
    os: 'Debian 12',
    lastDeploy: '2025-12-01',
  },
];

@Component({
  selector: 'docs-data-table-scroll-example',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [MlvDataTable, MlvDataTableCell, MlvBadge],
  templateUrl: './index.html',
  styleUrl: './index.scss',
})
export default class DataTableScrollExampleComponent {
  readonly servers = SERVERS;

  readonly columns: MlvDataTableColumn[] = [
    {
      key: 'host',
      title: 'Hostname',
      pinned: true,
      pinSide: 'left',
      width: '160px',
      sortable: true,
      filterable: true,
      pinnable: true,
    },
    {
      key: 'status',
      title: 'Status',
      pinned: true,
      pinSide: 'left',
      width: '110px',
      pinnable: true,
    },
    {
      key: 'region',
      title: 'Region',
      width: '130px',
      sortable: true,
      pinnable: true,
    },
    {
      key: 'cpu',
      title: 'CPU %',
      width: '100px',
      align: 'right',
      sortable: true,
      pinnable: true,
    },
    {
      key: 'memory',
      title: 'Mem %',
      width: '100px',
      align: 'right',
      sortable: true,
      pinnable: true,
    },
    {
      key: 'disk',
      title: 'Disk %',
      width: '100px',
      align: 'right',
      pinnable: true,
    },
    {
      key: 'network',
      title: 'Network',
      width: '120px',
      align: 'right',
      pinnable: true,
    },
    { key: 'uptime', title: 'Uptime', width: '120px', pinnable: true },
    {
      key: 'requests',
      title: 'Requests',
      width: '120px',
      align: 'right',
      sortable: true,
      pinnable: true,
    },
    {
      key: 'errors',
      title: 'Errors',
      width: '100px',
      align: 'right',
      sortable: true,
      pinnable: true,
    },
    {
      key: 'latency',
      title: 'Latency',
      width: '100px',
      align: 'right',
      pinnable: true,
    },
    { key: 'version', title: 'Version', width: '130px', pinnable: true },
    { key: 'os', title: 'OS', width: '140px', pinnable: true },
    {
      key: 'lastDeploy',
      title: 'Last Deploy',
      pinned: true,
      pinSide: 'right',
      width: '130px',
      sortable: true,
      pinnable: true,
    },
  ];
}
